- name: Adding mongoDB repositories
  yum_repository:
    name: MongoDB
    description: EPEL YUM repo
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc
    file: mongodbb

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: present

- name: Update MongoDB Listen Address
  notify:
    - Restart mongodb
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB service
  systemd:
    name: mongod
    enabled: yes
    state: started

- name: Downloading from github
  include_role:
    name: common
    tasks_from: from-github
  vars:
    APP_DIR: /tmp/mongodb-main
    EXTRACT_DIR: /tmp/



    