- name: Setup roboshop project -- Frontend Component
  hosts: FRONTEND
  become: yes
  tags:
    - frontend
  roles:
    - name: Load Frontend Role
      role: frontend


- name: Setup roboshop project -- MongoDB COMPONENT
  hosts: MONGODB
  become: yes
  tags:
    - mongodb
  roles:
    - name: Load MongoDb Role
      role: mongodb


- name: Setup roboshop project -- Catalogue Component
  hosts: CATALOGUE
  become: yes
  tags:
    - catalogue
  roles:
    - name: Load CATALOGUE Role
      role: catalogue


- name: Setup roboshop project -- Redis Component
  hosts: REDIS
  become: yes
  tags:
    - redis
  roles:
    - name: Load REDIS Role
      role: redis
