- name: Setup roboshop project -- Frontend Component
  hosts: FRONTEND
  become: yes
  tags:
    - frontend
  roles:
    - name: Load Frontend Role
      role: frontend


- name: Setup roboshop project -- MongoDB Component
  hosts: MONGODB
  become: yes
  tags:
    - mongodb
  roles:
    - name: Load MongoDb Role
      role: mongodb