- name: LOADING THE FRONTEND
  hosts: FRONTEND
  become: yes
  tags:
    - frontend
  roles:
  - name: loading the frontend
    role: frontend

- name: LOADING THE MONGODB
  hosts: MONGODB
  become: yes
  tags:
    - mongodb
  roles:
    - name: loading the mongodb
      role: mongodb