- name: Install NodeJS
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: installed

- name: Add Roboshop User
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop Project User


- name: Download Package
  include_role:
    name: common
    tasks_from: from-github
  vars:
    APP_DIR: /home/roboshop/catalogue
    EXTRACT_DIR: /home/roboshop

- name: copy content to actual directory
  copy:
    src: /home/roboshop/catalogue-main
    dest: /home/roboshop/catalogue/
    remote_src: yes
  become_user: roboshop

- name: Download NodeJS Dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop


- name: Copy SystemD file
  copy:
    src: catalogue.servicefile
    dest: /etc/systemd/system/catalogue.service

- name: Start  Mongodb Service
  systemd:
    name: catalogue
    state: restated
    enabled: yes
    demoan_reload: yes





